Algoritmo "logico"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2024
Var
// Seção de Declarações das variáveis 
  a, b:real
  result: logico

Inicio
a <- 8.5
b <- 10.2
result <- (a*4/2)+b > a+b)

escreva("Result = ", result)
Fimalgoritmo